### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by dbpolito** [fireworkweb/docker-dind#1]
### TODOs

- [ ] 1. Maybe we could use alpine default image and:
- [ ] 2. Copy docker bin: https://github.com/docker/compose/blob/master/Dockerfile#L11
- [ ] 3. Download built bin: https://docs.docker.com/compose/install/#alternative-install-options
